- url.c
the man page states:
"If you are going to verify detached signatures, make sure that the
program knows about it; either give both filenames on the command
line or  use  '-' to specify STDIN.".
To comply to this, we also  pass the file to be verified into the command line.
> gpg 2.1.1 became stricter with the usage of --verify:

- auto2.c
- linuxrc.c
- url.c
As a result of bnc #901598 we would now get a warning dialog when using a plain rpm in the 'dud' option. This is fixed in two steps: (1) count rpms a driver updates internally and (2) verify the rpm signature (duds must be signed unless you run in 'insecure' mode).
> Bnc 901598 2

- file.c
On PowerNV IPAPPEND looks like just a mac, so it is _NOT_ prefixed
with 01- or whatsoever.
Let's handle that case in linuxrc
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
> Fix BOOTIF on PowerNV

- .gitignore
- install.c
Display the main menu directly.
Tested with `sudo ./mksusecd --micro --initrd /tmp/initrd --create /tmp/test.iso openSUSE-13.2-DVD-x86_64.iso`, after aborting the installation the error message is skipped and the main menu is displayed.
> Do not display an error message after aborting YaST (bsc#614829)

- global.h
- linuxrc.c
- url.c
an 'extend' command (bsc #936068)
> - avoid any interactive dialogs when checking the digest of files during

- install.c
revert a bit of the last change
> s390x: keep ssh active when selecting vnc (bsc #943744)

- dialog.c
- file.c
- file.h
- global.h
- linuxrc.c
- settings.c
Also, make the actual shell command used configurable via debugshell option.
> get rid of 'no job control' bash messages (bsc #945607)

- file.c
Proposed fix for Bugzilla # 937437.
> Modified file.c to only accept valid types of OsaInterface (bsc#937437)

- util.c
The workaround for ppc64 with definiing it including O_DIRECTORY
is not enough, since its actually the bit for the incorrect
O_DIRECTORY that causes it to be rejected as EINVAL by the
kernel for aarch64.
> Workaround O_TMPFILE definition on SLE12 / aarch64 (bsc#965068)

- file.c
- global.h
- linuxrc.html
- net.c
Removed all the code that asks for an OSA Portname
If a Portname is found in the parameters, output a message saying it's deprecated
Updated linuxrc.html to indicate that Portname is deprecated
Updated linuxrc.html to also indicate that OsaMedium was deprecated, since people are still specifying it
Tested the changes on s390lp1
> Made the following changes for FATE#320112

- linuxrc.c
On architectures like aarch64 which use 64k pagesize, we're
running very quickly against inode limits otherwise.
> Do not limit number of inodes in tmpfs overlay

- util.c
A fixed glibc has been submitted and the workaround is no longer needed.
> remove O_TMPFILE workaround needed for bsc #964709 and bsc #965068

- linuxrc.c
- net.c
Added verbiage to the prompt for the MAC address when a Layer 2 NIC
is being used. In most cases the user shouldn't specify one and take
the default.
This builds fine on all architectures and tested fine on s390x.
> Updated the copyright information that is displayed on the console.

- file.c
Autoyast looks for an 'AutoUpgrade' option instead of 'Upgrade' for historical reasons. So be nice and turn Upgrade into AutoUpgrade .
> activate AutoUpgrade if Upgrade + AutoYaST are set (bsc #978252)

- dialog.c
- settings.c
- util.c
- util.h
linuxrc was looping on closed stdin and writing to broken stdout. So, make sure IO works again when we return from sh.
> restore standard IO file descriptors when returning from external shell (bsc #983014)

- install.c
instsys id reading didn't work due to this typo and so the check for the correct instsys didn't work.
> fix reading instsys id (related to bsc #974601)

- file.c
- file.h
- global.h
- linuxrc.c
- util.c
We do this by asking wicked for ibft interfaces and adding them to
the 'initial' devices list. That list holds the interfaces that have a fixed
config that must not be modified by linuxrc.
same as https://github.com/openSUSE/linuxrc/pull/117 but for sle12-sp2 branch
> don't configure ibft devices in linuxrc (bsc #997598)

- file.c
Obviously it needs to be parsed before we start to configure the network...
> parse netwait option earlier (bsc #995304)

- file.c
- net.c
- net.h
[bsc#997913](https://bugzilla.suse.com/show_bug.cgi?id=997913)
Basically, ensure we operate on the correct interface. For this, append
before and remove after real network interface operations the '.vlanid'
appendix on the interface name (net.config.device variable).
> make sure the correct interface is used when vlan is active (bsc #997913)

- linuxrc.c
We've been asked to disable the self-update feature by default in SLE 12 SP2.
> Disable self-update feature by default

- file.c
- file.h
- global.h
- linuxrc_yast_interface.txt
These options are not used in YaST anymore, removing the dead code.
> Clean up: removed "regcert", "smturl" and "smtcert" options (bsc#943966)

- file.c
- file.h
- global.h
- install.c
- linuxrc.c
- settings.c
- util.c
- util.h
It's used with either block or char dev as arg: linuxrc.core=block_dev|char_dev.
For a block dev, the device is mounted and core files created there. For a char dev,
the uuencoded core is written to it (think of serial line).
> add linuxrc.core option to enable core dumps in linuxrc (to debug bsc #1010505)

- linuxrc_repo.md
- url.c
https://fate.suse.com/322286
linuxrc will check for /content first and when it's missing, check for /repodata/repomd.xml.
> have linuxrc accept plain repomd repo as install source (fate #322286)

- auto2.c
- linuxrc_repo.md
- url.c
This works by extending the /boot/ARCH/config file syntax (see docs):
Appending '?copy=1' to a component tells linuxrc that this is not an image
to mount but a file to copy to the '/' directoy.
> allow reading of config files from instsys location (/boot/ARCH/) (fate #322283)

- display.c
- url.c
There was a memory management issue when showing the progress bar window.
Already freed memory might have been reused.
> fix segfault when loading installer (bsc #1033441)

- auto2.c
- file.c
- file.h
- global.h
- url.c
- util.c
This includes downloading and parsing repomd.xml to find ot the real file name
and file checksum.
This reuses the existing **very** limited xml parser file_parse_xmllike() which
seems sufficient here.
> read license.tar.gz from repomd repositories (fate #322286)

- global.h
- keyboard.c
linuxrc uses static arrays for its textmode dialogs. The boundary check for
too large screens exsisted but was not always employed.
> enforce linuxrc's maximum screen dimensions properly (bsc #1027354)

- util.c
The location is (historically) different on x86 compared to other
architectures. The 'else' branch was just missing.
> set kernel and initrd to use with kexec option (bsc #1044683)

- Makefile
when building packages
(random) filesystem order of input files
influences ordering of functions in the output,
thus without the patch, builds (in disposable VMs) would differ.
See https://reproducible-builds.org/ for why this matters.
https://bugzilla.opensuse.org/show_bug.cgi?id=1041090
> sort input files (boo#1041090)

- file.c
- global.h
- linuxrc_yast_interface.txt
SetHostnameUsed is set if the user has used the SetHostname option
explicitly to change its value.
Note that this not only means via kernel command line but also includes
config files like linuxrc.config or an info file.
> add SetHostnameUsed entry to install.inf (bsc #1054933)

- linuxrc.c
- net.c
Persistent device configuration - installer part
Provide a common mechanism to achieve persistent configuration of System z devices that last across reboots and also integrates with the existing s390-tools.
> Fate322567

- .travis.yml
- Dockerfile
- file.c
- file.h
- git2log
- global.h
- keyboard.c
- linuxrc_yast_interface.txt
- smoke_test.sh
- util.c
- Added a new handler for the `media_upgrade` boot option ([fate#323163](https://fate.suse.com/323163))
- Added a basic Travis support (does not build the RPM, just compiles the sources), but at least something...
- The `git2log` script has been updated to handle detached Git HEAD in Travis build (just updated from the [linuxrc-devtools](https://github.com/openSUSE/linuxrc-devtools) repository)
Added a simple smoke test to ensure `linuxrc` can be started and does not crash.
- The test covers both the line mode and the interactive mode
-  See an [example Travis log](https://travis-ci.org/openSUSE/linuxrc/builds/291400319#L975) for the result
- Unfortunately Travis does not display the screen dump well, but it is still somehow readable (the colors are bit broken, too big line spacing, the …
> Support for "media_upgrade" boot option (fate#323163), enabled Travis, added smoke test

- file.c
Otherwise you'll never be able to clear the list entirely.
see https://bugzilla.suse.com/show_bug.cgi?id=1058065#c10
> update broken module config even if list is empty

- linuxrc.c
Since kernel 4.14, we see:
```
squashfs: Unknown symbol ZSTD_DStreamWorkspaceBound (err 0)
squashfs: Unknown symbol ZSTD_decompressStream (err 0)
squashfs: Unknown symbol ZSTD_initDStream (err 0)
```
So install the modules if they exists prior loading squashfs.
> squashfs.ko might depend on zstd_decompress

- file.c
- file.h
- linuxrc.c
- linuxrc_repo.md
- url.c
The new media layout has a 'CHECKSUMS' file instead of the old 'content'.
> read digests also from CHECKSUMS file

- url.c
When removing a 'duplicate' entry ensure it really has the same device name.
Else we might drop too many.
> fix network interface handling (bnc #1068336)

- auto2.c
- linuxrc.c
- util.c
For this, the -s option should be used. See discussion in [bsc \#1075051](https://bugzilla.suse.com/show_bug.cgi?id=1075051) for details.
> allow kexec to work with secure boot (bsc #1075051)

- auto2.c
- auto2.h
- global.h
- install.c
- linuxrc.c
- url.c
This patch adds
- kexec=2: check if instsys does not match, then present a user dialog
- kexec=3: check, but skip the dialog
The default is now kexec=2.
> extend 'kexec' option to allow updating kernel/initrd only if necessary (bsc #990374)

- auto2.c
- util.c
Until upstream comes around we need a working solution. Until then, pass
different parameters to kexec.
> be carefull with 'kexec -s', it's not always available (bsc #1076839)

- net.c
Handle LCS devices separate from CTC devices now that we're using the zdev commands.
Change chzdev call to conform to documented syntax
> Fix for bsc#1085860

- auto2.c
- util.c
Finally: you always have to use the new '-a' option.
> kexec uses '-a' option now (bsc #1076839)

- auto2.c
For network mountable url schemes the call to net_activate_s390_dev() was
simply missing.
> activate s390 devices when reading driver updates via nfs & cifs (bsc#1089937)

- file.c
Apparently 1024 is not enough - so let's not assume any limit.
> don't impose limits on /proc/cmdline size (bsc #1092154)

- url.c
Taken from https://github.com/openSUSE/linuxrc/pull/149.
> fix segfault when using an invalid url scheme (bsc #1061824, bsc #1098443)

- README.md
linuxrc doesn't build without that package. It's there in the .spec file, but not in the instructions in the README.md.
> Added new BuildRequires to devel doc

- file.c
- file.h
- global.h
- url.c
- util.c
Documentation:
https://en.opensuse.org/SDB:Linuxrc
> NoRepo
>
> Disable the repo location check and do not write a ZyppRepoURL to /etc/install.inf; expect YaST to take care of the repo selection.
>
> This is useful for delegating the repo selection to the registration server so a user can simply enter a registration code first, then the matching product will be automatically selected based on that registration code, and the respective repos will be addded accordingly (Fate#325482).
> Added parameter norepo (fate#325482)

- url.c
GCC 9 starts to optimize undefined behaviour code as seen here:
https://www.gnu.org/software/gcc/gcc-9/porting_to.html#complit
> Fix usage of a out-of-scope vector constructor.

- net.c
On s390, answering 'No' in the 'Do DHCP?' dialog leads not to the static setup dialog but to no network.
- bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1124654
- Scrum card: https://trello.com/c/bzchqEQA
The issue was caused by an incorrect workflow when VLAN is used.
Note that the expected correct behavior here is **not** to ask for DHCP at all but to do it automatically.
> fix network dialog workflow when VLAN is active (bsc #1124654)

- file.c
- file.h
- global.h
- linuxrc.c
- util.c
https://bugzilla.suse.com/show_bug.cgi?id=1132688
https://trello.com/c/0S3qkpcj
Introduce [`autoassembly`](https://en.opensuse.org/SDB:Linuxrc#p_autoassembly) boot option.
The default is 1 (enable). So unless `autoassembly=0` is explicitly given, nothing changes.
https://github.com/openSUSE/installation-images/pull/311
> add 'autoassembly' boot option to prevent MD/RAID autoassembly (bsc #1132688)

- file.c
- file.h
- global.h
- linuxrc.c
- util.c
_This is a backport of PR #188._
https://trello.com/c/A1orfA6C/1135-2-sle12-sp5-p2-1138583-error-disk-remove-partition-failed-occurred-while-installing-on-multipath-setup
https://bugzilla.suse.com/show_bug.cgi?id=1138583
https://github.com/openSUSE/linuxrc/pull/188
Cherry-picked both commits of that PR and fixed the conflicts (no "NoRepo" option in this branch).
> Backport: add 'autoassembly' boot option to prevent MD/RAID autoassembly (bsc #1132688)

- linuxrc.c
https://trello.com/c/h92INIpW/1087-1-15-sp2-make-autoassembly0-the-default-setting-in-sle-15-sp2
https://bugzilla.suse.com/show_bug.cgi?id=1132688
Auto-assembly of RAIDs during installation happens at the most inconvenient times, often clashing with operations that libstorage-ng / yast-storage-ng are doing.
Disable auto-assembly. Linuxrc now has a command line option for that; until now, auto-assembly was enabled by default. This commit changes that.
> Disable MD/RAID auto-assembly by default (bsc#1132688)

- Dockerfile
- linuxrc_repo.md
- url.c
- Added support for a multi-repository installation medium (like the Packages DVD)
- Do not fail when the installation medium does not contain a SUSE tags or a RPM-MD repository but contains the repositories in subdirectories (indexed in the `/media.1/products` file)
- https://bugzilla.suse.com/show_bug.cgi?id=1141889
- Tested manually with a custom built DVD installation image (Packages DVD + copied boot files from the Installer DVD + updated linuxrc)
- Works fine, does not complain about a missing repository
- The `/etc/install.inf` contains the correct `ZyppRepoURL` value as expected
- Updated the `Dockerfile` to use the newer image built directly in OBS
- Updated documentation
- SUSE tags repositories are obsolete since SLE15/Leap15
- Documented multi-repository medium
- Documented …
> Support for a multi-repository installation medium (bsc#1141889)

- util.c
https://bugzilla.suse.com/show_bug.cgi?id=1145625
'Boot linux system' boot option does not work on aarch64.
When booting 'installed system' linuxrc has to pick the correct kernel/initrd pair. Unfortunately the kernel naming scheme differs for each architecture.
[Backport to SLE12-SP5](https://github.com/openSUSE/linuxrc/pull/194)
> choose correct kernel image on aarch64 (bsc#1145625)

- auto2.c
- file.c
- file.h
- global.h
- linuxrc.c
- linuxrc_and_autoyast.md
- slp.c
- url.c
- util.c
Scrum card: https://trello.com/c/7tgF4mpl
Support AutoYaST url schemes in linuxrc and evaluate the `autoyast` boot option in linuxrc.
Look at the details in 
https://github.com/openSUSE/linuxrc/blob/0830145d6740e437bd5b5681a38dfddb8eac1801/linuxrc_and_autoyast.md
* autoyast url scheme doc
*   - https://doc.opensuse.org/projects/autoyast/#Commandline.ay
*
* actual implementation
*   - https://github.com/yast/yast-installation/blob/master/src/lib/transfer/file_from_url.rb
*   - https://github.com/yast/yast-autoinstallation/blob/master/src/modules/AutoinstConfig.rb
> support autoyast url schemes in linuxrc

- auto2.c
When using the `autoyast2` option, no `AutoYaST` entry in `install.inf` is created.
- https://bugzilla.suse.com/show_bug.cgi?id=1157031
This patch restores the old autoyast2 behavior: download the file (no rules and classes) and pass the downloaded file to yast. The 2nd step was missing.
> ensure autoyast url is passed to yast when autoyast2 option is used (bsc #1157031)

- url.c
While testing fix https://github.com/openSUSE/linuxrc/pull/199 for https://bugzilla.suse.com/show_bug.cgi?id=1156967 an issue with the `label` URL scheme was uncovered.
`autoyast=label://label_foo/bar.xml` does not work.
Fix parser (`server` var was not reset after use).
> fix 'label' URL scheme parsing

- global.h
- scsi_rename.h
The option will be default in GCC 10 and it fixes:
```
/usr/bin/ld: checkmedia.o:/home/marxin/Programming/linuxrc/global.h:739: multiple definition of `config'; auto2.o:/home/marxin/Programming/linuxrc/global.h:739: first defined here
/usr/bin/ld: dialog.o:/home/marxin/Programming/linuxrc/global.h:739: multiple definition of `config'; auto2.o:/home/marxin/Programming/linuxrc/global.h:739: first defined here
/usr/bin/ld: display.o:/home/marxin/Programming/linuxrc/global.h:739: multiple definition of `config'; auto2.o:/home/marxin/Programming/linuxrc/global.h:739: first defined here
/usr/bin/ld: file.o:/home/marxin/Programming/linuxrc/global.h:739: multiple definition of `config'; auto2.o:/home/marxin/Programming/linuxrc/global.h:739: first defined here
/usr/bin/ld: …
```
> Fix building with -fno-common.

- Makefile
- mkpsfu/Makefile
I would like the package would respect $Optflags in OBS.
Thus I'm suggesting to append EXTRA_CFLAGS to CFLAGS. One can
then 'export EXTRA_CFLAGS=$Optflags'.
> Append EXTRA_CFLAGS to CFLAGS.

- Makefile
- mkpsfu/Makefile
https://bugzilla.suse.com/show_bug.cgi?id=1158996
On some ppc64le setups, linuxrc runs into "stack smashing detected" and crashes.
Revert https://github.com/openSUSE/linuxrc/pull/204. This avoids compiling with `$RPM_OPT_FLAGS`.
That's of course not the final solution but it gets linuxrc going until the real cause has been identified.
> Revert "Append RPM_OPT_FLAGS to CFLAGS." (bsc#1158996)

- Makefile
- auto2.c
- linuxrc.c
- mkpsfu/Makefile
- util.c
- https://bugzilla.suse.com/show_bug.cgi?id=1158996
- https://trello.com/c/UpuZNwxv
The `extend` command hangs forever on ppc64 due to a stack smashing by glibc's `backtrace()` function. The stack smashing was revealed by the stack protection options included in `$RPM_OPT_FLAGS`.
- Rework `extend` so it doesn't wait forever for linuxrc to finish. Instead it returns an error if a crash happens.
And, since glibc has been fixed:
- Re-enable `$RPM_OPT_FLAGS`.
> rework 'extend' command to log and report an error if linuxrc unexpectedly crashes (bsc#1158996)

- linuxrc.c
subroutine, and moved the invocation of it until after the call to
lxrc_add_parts so that the squashfs files have been loopback mounted.
> For bsc#1161701, Moved the logic to retrieve the platform name into a

- linuxrc.c
- https://bugzilla.suse.com/show_bug.cgi?id=1163115
- https://trello.com/c/ms95Xya0
installation stalls after loading the inst-sys images because `plymouth quit` hangs indefinitely.
This is because [get_screen_size()](https://github.com/openSUSE/linuxrc/blob/master/keyboard.c#L477) might potentially interfere with plymouthd as both linuxrc and plymouthd might try to read from the same serial line.
It is however unclear why  plymouthd runs on a serial line as it is started with `plymouthd --tty=tty1` which should restrict it to `/dev/tty1`. But apparently this does not work since sle15-sp1.
- https://bugzilla.suse.com/show_bug.cgi?id=1164123
Start plymouthd after all the console init stuff has been done by linuxrc to be on the safe side.
The same for SLE15-SP1: …
> move plymouthd start after screen size detection (bsc #1163115)

- .travis.yml
- file.c
- global.h
- linuxrc.c
- net.c
- url.c
- https://trello.com/c/WJmotQTM
Add ´try` keyword to `ifcfg` option.
This is the parser code from https://github.com/openSUSE/linuxrc/pull/217 but using the simpler approach of copying the ifcfg value to `config.ifcfg.manual` - which is already used for exactly the intended purpose (iterating through network device list until an interface works).
> parse 'try' keyword in ifcfg option (jsc#SLE-8965, jsc#SLE-9791)

- dialog.c
- dialog.h
- file.c
- file.h
- global.h
- linuxrc.c
- settings.c
- util.c
- util.h
- https://bugzilla.suse.com/show_bug.cgi?id=1168036
- https://jira.suse.com/browse/SLE-7396
I/O device pre-configuration should not be used unconditionally. The user needs a way to avoid it.
Add a `DeviceAutoConfig` boot option which can be 0, 1, 2, resp. `no`, `yes`, `ask`.
If set to `ask` and pre-config data is avaibale, the user gets a confirmation dialog before using the device pre-config data. The default is `ask`.
There is also a menu item in `Main Menu -> Settings` that allows to apply the pre-config data manually.
- related installation-images change: https://github.com/openSUSE/installation-images/pull/368
```
>>> SUSE Linux installation program v7.0.13 (c) 1996-2020 SUSE LLC  <<<
Loading basic drivers... ok
Apply I/O device auto-configuration?
0) <-- Back <--
1) Yes
2) No
> 
``` …
> make I/O device pre-configuration optional (bsc#1168036, jsc#SLE-7396)

- linuxrc_repo.md
single-letter options are useful when typing, but long-named options are
better for documenting (no need to look for man pages).
> Use long-named options for better readability

- net.c
- https://bugzilla.suse.com/show_bug.cgi?id=1171587
s390x device activation doesn't work correctly in TW.
There was a usage of `/sbin/udevadm` left in the s390x network device setup code.
> udevadm is in /usr/bin (bsc#1171587)

- global.h
- linuxrc.c
- url.c
- url.h
- util.c
- util.h
- https://bugzilla.suse.com/show_bug.cgi?id=1171018
- https://trello.com/c/kxbkRRjE
After installation, the user might end up with two repositories: one containing `$releasever`, the other with the replaced value. 
linuxrc replaces `$releasever` with the actual product version in URLs. Similar to what libzypp does.
linuxrc does not use `/etc/products.d/baseproduct` to read the version (since that is not available during installation) but uses `/usr/lib/os-release::VERSION_ID`.
linuxrc doc update:
- https://en.opensuse.org/SDB:Linuxrc#Parameter_Reference
This works by keeping a copy of the essential parts of the URL before replacing the zypp variables. The stored values are then used when constructing the zypp URL to pass to yast.
There's no good way to just keep a copy of the full URL as …
> replace $releasever in URLs, similar to libzypp (bsc#1171018)

- file.c
- file.h
- util.c
- util.h
- https://bugzilla.suse.com/show_bug.cgi?id=1168036
- https://trello.com/c/if9ZgetC
If the user turns off s390 device auto-config, set also `rd.zdev=no-auto` in the target system.
If the system has auto-config data and the user passes `deviceautoconfig=0` or turns off auto-config in a linuxrc dialog,
add `rd.zdev=no-auto` to the boot options.
Also, make linuxrc accept `rd.zdev=no-auto` as alias for `deviceautoconfig=0`.
Note: there is no `rd.zdev=auto` option.
- https://www.ibm.com/support/knowledgecenter/linuxonibm/com.ibm.linux.z.lkdd/lkdd_c_auto_available.html
> s390: set rd.zdev=no-auto if auto-config has been turned off (bsc#1168036)

- global.h
- net.c
- https://jira.suse.com/browse/SLE-15770
- https://trello.com/c/2cxWqhj0
Installer should be able to send DHCP request in RFC2132 format, if needed.
Add `rfc2132` option to ifcfg config parameters. For example
```
ifcfg=eth0=dhcp,rfc2132
```
This will create an `ifcfg-eth0` file that looks like this:
```
BOOTPROTO='dhcp'
DHCLIENT_CREATE_CID='rfc2132'
STARTMODE='auto'
```
wicked allows also other values for `DHCLIENT_CREATE_CID`. For these, no shortcut exists. You can specify the option explicitly if needed. For example
```
ifcfg=eth0=dhcp,DHCLIENT_CREATE_CID=rfc4361
```
- related wicked implementation: https://github.com/openSUSE/wicked/pull/843
> add rfc2132 keyword to ifcfg option (jsc#SLE-15770, jsc#SLE-15488)

- file.c
- file.h
- global.h
- install.c
- linuxrc.c
- module.c
- https://bugzilla.suse.com/show_bug.cgi?id=1174912
- https://trello.com/c/odtwPIg0
Add `insmod.pre` option to linuxrc.
The purpose if this option is to give the user an opportunity to load modules before udevd is started. The existing `insmod` option runs too late for that.
> add insmod.pre option to linuxrc (bsc#1174912)

- file.c
- file.h
If linuxrc sees options of the form `foo.bar=xxx` it assumes `bar=xxx` to be a kernel module option for `foo`.
This was broken as linuxrc did this sometimes also when `foo` was a valid linuxrc option.
> fix linuxrc module option parsing

- util.c
- https://bugzilla.suse.com/show_bug.cgi?id=1141875
In debug mode, linuxrc defaults to adding `--real-mode` as option to kexec. That's a very old option and rather strange in modern times.
Remove it.
> do not offer --real-mode as kexec option in debug mode  (bsc#1141875)

- linuxrc.c
for non-x86 architectures, only /sys/firmware/efi/efivars remains
So, check both to know if we are running on EFI boo#1180408
> Since kernel 5.10, /sys/firmware/efi/vars has been dropped

- module.c
- https://bugzilla.suse.com/show_bug.cgi?id=1180792
- https://trello.com/c/x1LXNeEn
1. When leaving the `Expert -> Kernel Modules (Hardware Drivers)` menu a stack smashing might be detected. The internal array was one item too small in some situations.
1. If a module has a very long description (try `modinfo sbc_epx_c3`) a buffer overrun might occur.
1. In some code paths module loading missed the actual module loading.
1. Rewriting the code to guard against this in future. It's still a static array but reasonably ensured the length is correct.
1. use `asprintf`
1. fix code flow
> fix writing out of menu item array bounds (bsc#1180792)

- linuxrc.c
- module.c
- module.h
- util.c
- https://bugzilla.suse.com/show_bug.cgi?id=1180792
- https://trello.com/c/x1LXNeEn
Code cleanup to avoid static string buffers in module code.
This is a follow-up to https://github.com/openSUSE/linuxrc/pull/241 and extends https://github.com/openSUSE/linuxrc/pull/238.
> cleanup module code to avoid static string buffers (bsc#1180792)

- file.c
- file.h
- global.h
- linuxrc.c
- linuxrc_yast_interface.txt
- util.c
Allow moving the root file system into a zram device and/or enable swapping to a zram device.
- https://jira.suse.com/browse/PM-2253
- https://trello.com/c/DawiPzcU
Use these boot options:
- `zram.root=SIZE`: move root fs into a zram device of size `SIZE`
- `zram.swap=SIZE`: before starting YaST, enable swapping to a zram device of size `SIZE`
- `zram=1`: a shorthand for `zram.root=1G zram.swap=1G` (this is the default)
- `zram=0`: disable zram use
`SIZE` is something like `512M` or `1G`.
- adjusted installation-images package: https://github.com/openSUSE/installation-images/pull/462
- zram documentation: https://www.kernel.org/doc/html/latest/admin-guide/blockdev/zram.html
- the changes do not affect the non-zram workflow
- the zram root fs device is formatted as ext2
- zstd compression …
> support using zram device as root file system (jsc#PM-2253)

- auto2.c
- util.c
- https://bugzilla.suse.com/show_bug.cgi?id=1180161
- https://trello.com/c/0zqcWVhD
When linuxrc needs to set up a loop device it crashes if the file name is a bit longish (>= 64 chars).
This happens because the kernel's `loop_info` struct has a file name field `char lo_name[LO_NAME_SIZE]` with `LO_NAME_SIZE = 64`.
Use `strncpy`.
Check remaining `strcpy` uses.
> fix buffer overflow when setting up loop device (bsc#1180161)

- linuxrc.c
After some discussion in https://jira.suse.com/browse/PM-2253, the zram feature will be accepted into sle15-sp3 if it is disabled by default.
We will change the default for Tumbleweed to 'enabled' later.
> Revert "default to using zram"

- file.c
- file.h
- global.h
- url.c
- util.c
- https://bugzilla.suse.com/show_bug.cgi?id=1183368
- https://github.com/yast/yast-installation/issues/925
Add `extend` option to linuxrc to be able to load additional inst-sys parts. An inst-sys part is any file that is available on the installation medium in the `/boot/ARCH` directory.
The argument is a comma (',') separated list. If a part is preceded with a '?' it marks this part as optional (linuxrc will not abort the installation if it is missing).
- load `foo` and `bar` extensions
```
extend=foo,bar
```
- load `foo` and (optionally, if it exists) `bar`
```
extend=foo,?bar
```
Note that several `extend` options override each other. So don't do `extend=foo extend=bar`, rather do `extend=foo extend=+bar` if really necessary.
> add 'extend' option (bsc#1183368)

- linuxrc.c
Do not create directories in / that are subject to usrmerge
> fix rescue image in usrmerge case (boo#1029961)

- linuxrc.c
Testing showed very positive results so far. Make `zram=1` the default.
> default to using zram

- module.c
- module.h
- util.c
- https://bugzilla.suse.com/show_bug.cgi?id=1184550
- https://trello.com/c/iroG0VHx
Kernel modules in driver updates are not handled correctly. Due to the `*.ko` to `*.ko.xz` extension change.
Be more careful and anticipate either variant in driver updates.
> fix handling of modules in driver updates (bsc#1184550)

- net.c
- https://bugzilla.suse.com/show_bug.cgi?id=1185304
- https://trello.com/c/2yMZcrbI
Even if `ssh.password.enc` is set, linuxrc asks for a password.
> don't ask for ssh password if ssh.password.enc is set (bsc#1185304)

- linuxrc.c
modules and firmware need to belinked from either /lib or /usr/lib
depending on usrmerge. Leave that to the script in installation-images
> rescue: leave linking modules to prep script

- global.h
- url.c
- util.c
- https://bugzilla.suse.com/show_bug.cgi?id=1187014
- https://trello.com/c/IbMHDdRx
If a network URL passed to linuxrc is not valid, linuxrc will iterate trough all available network interfaces trying them in turn to read the data. During this iteration, a memory corruption may happen.
linuxrc holds all hardware probing data in `config.hd_data` and the iteration goes over a linked list anchored there.
During the iteration linuxrc may implicitly trigger an `update_device_list` function which will update the hardware data in `config.hd_data` - but only if udev events have been processed since the last call to `update_device_list`.
Unfortunately, udev events are not only generated by new hardware during this period - and if this happens, it completely breaks the iteration loop.
Introduce a …
> prevent memory corruption while iterating through network device list (bsc#1187014)

- auto2.c
Port https://github.com/openSUSE/linuxrc/pull/268 to SLE15-SP3.
- https://bugzilla.suse.com/show_bug.cgi?id=1187235
- https://trello.com/c/jRFPOOAW
If linuxrc is passed an `autoyast` option for a rules-based setup, e.g. `autoyast=http://example.com/bar/profiles/` it cannot retrieve that url to test the network connection - because it's a directory.
This leads to the situation that linuxrc may skip the network setup (it doesn't need it in this case).
Assume that a file `rules/rules.xml` exists below the specified directory and try to retrieve that instead. linuxrc does not parse the file, it is only read to ensure the network connection is working.
It is also possible to pass a directory to the `autoyast` option with the intention to select the profile based on the ip or mac address. See …
> read rules.xml if autoyast option indicates a rules-based setup (bsc#1187235)

- url.c
- https://bugzilla.suse.com/show_bug.cgi?id=1188186
linuxrc may still loose query paraters in URLs. This can happen if the URL is processed **internally** and the URL is re-calculated from its parsed parts.
The older fix referenced below handles only the situation when the URL is passed on to external tools.
First attempt:
- https://bugzilla.suse.com/show_bug.cgi?id=1169492
- https://github.com/openSUSE/linuxrc/pull/222
> fix handling of query parameters (bsc#1169492, bsc#1188186)

- url.c
- https://jira.suse.com/browse/SLE-17026
linuxrc doesn't allow proper proxy authentication.
Set proxy authentication method explicitly in libcurl.
And the same for HTTP/HTTPS (without proxy).
See `CURLOPT_HTTPAUTH(3)` for technical details.
> let curl figure out proper authentication method (jsc#SLE-17026)

- module.c
Add .ko.gz and .ko.zst to the mod_extensions array. Thanks for
having coded this with future extension in mind!
> Add support for gz and zst compressed modules

- global.h
- https://trello.com/c/BV5JkVBk
- dev: https://jira.suse.com/browse/SLE-19610
- epic: https://jira.suse.com/browse/SLE-18631
Until now you'd have to specify netsetup=vlanid to get it.
From the epic: "Based on our experience with customers the large majority has VLAN segmented networks. If we can have this option available by default it might prevent some frustration for customers not 100% familiar with the SLES specifics."
Documented at <https://en.opensuse.org/SDB:Linuxrc#p_netsetup>
> s390x: ask for the VLAN id by default (jsc#SLE-18631, jsc#SLE-19610)

- linuxrc.c
- https://bugzilla.suse.com/show_bug.cgi?id=1189707
- https://bugzilla.suse.com/show_bug.cgi?id=1191203
Use zram during installation.
This was already implemented for SP3 but not made the default. To avoid further memory shortage related issues, make zram usage the default in SP4.
> default to using zram (bsc#1191203, #bsc1189707)

- module.c
- https://bugzilla.suse.com/show_bug.cgi?id=1192855
- https://jira.suse.com/browse/SLE-21256
Port https://github.com/openSUSE/linuxrc/pull/273 to sle15-sp4.
Kernel moves to zstd compression for modules and initrd. Add .ko.gz and .ko.zst to the mod_extensions array.
> Add support for gz and zst compressed modules (jsc#SLE-21256, bsc#1192855)

- settings.c
- Epic: https://jira.suse.com/browse/SLE-21107
- Dev task: https://jira.suse.com/browse/SLE-22101
- Trello: https://trello.com/c/4sCajesT/2728-feature-linuxrc-the-new-kbd-package
Since _kbd-legacy_ is now deprecated and will be removed soon, this makes sure to only rely on keyboard maps that are available from the new _kbd_ package; those below `/usr/share/kbd/keymaps/xkb`.
Fortunately, _linuxrc_ already used mostly keymaps from there. There were just a few exceptions:
- "uk" is now "gb"
Those are still needed, but not yet in the new _kbd_ package:
- Greek
- Russian
So we will need to keep _kbd-legacy_ for those languages until there is a proper replacement in the new _kbd_ package.
https://github.com/yast/yast-country/pull/288
> Migration away from kbd-legacy (jsc#SLE-21107)

- dialog.c
- dialog.h
- file.c
- file.h
- global.h
- install.c
- keyboard.c
- keyboard.h
- linuxrc.c
- module.c
- util.c
- https://bugzilla.suse.com/show_bug.cgi?id=1193910
- https://jira.suse.com/browse/SLE-18632
- https://trello.com/c/LX0JUO1E
(1) This dialog:
```
Select the display type.
0) <-- Back <--
1) X11               
2) VNC               
3) SSH               
4) ASCII Console          
>  4
```
is misleading and should be reworked (you get the graphical Qt UI choosing 4).
(2) The dialog should be shown on `/dev/tty1` if a framebuffer exists on s390x (and not on the serial line).
- https://github.com/openSUSE/installation-images/pull/564
- https://en.opensuse.org/SDB:Linuxrc#p_switch_to_fb
1. Enable the dialog on all architectures. For better testing and it might be useful anyway. You get the dialog by adding `netsetup=display` to the boot options (on s390x this is the default setting).
2. Switch …
> enable display dialog for all architectures

- global.h
Port https://github.com/openSUSE/linuxrc/pull/275 to SLE15-SP4.
- https://trello.com/c/BV5JkVBk
- dev: https://jira.suse.com/browse/SLE-19610
- epic: https://jira.suse.com/browse/SLE-18631
Until now you'd have to specify netsetup=vlanid to get it.
From the epic: "Based on our experience with customers the large majority has VLAN segmented networks. If we can have this option available by default it might prevent some frustration for customers not 100% familiar with the SLES specifics."
Documented at <https://en.opensuse.org/SDB:Linuxrc#p_netsetup>
The network setup is affected by several boot time options.
When I use just `netsetup=1`,  there is a new VLAN question before the DHCP question.
When I use just `install=http...`, DHCP happens automatically and no VLAN question is asked.
The …
> s390x: ask for the VLAN id by default (jsc#SLE-18631)

- util.c
Port https://github.com/openSUSE/linuxrc/pull/285 to SLE15-SP3.
- https://bugzilla.suse.com/show_bug.cgi?id=1196061
Allow installation repository to be on RAID devices.
Adding `autoassembly=1` as boot option and using (for example) `install=hd:/foo/bar.iso` should find the installation repo even if it's located on a RAID volume.
Setting the `list_md` flag for hardware probing ensures RAID devices are included in the disk list.
- https://en.opensuse.org/SDB:Linuxrc#p_autoassembly
> check also raid devices for install repo (bsc#1196061)

- auto2.c
- file.c
- install.c
- url.c
- url.h
Port https://github.com/openSUSE/linuxrc/pull/286 to SLE15-SP3.
- https://bugzilla.suse.com/show_bug.cgi?id=1196061
- https://trello.com/c/bC5yVZas
linuxrc traditionally leaves the installation medium mounted when starting yast. This is not strictly necessary.
Do not do this, as this interferes with YaST's media handling and extension loading via `extend`.
> do not leave repository mounted when starting yast (bsc#1196061)

- Makefile
- edid-write/Makefile
- edid-write/edid-write.c
- file.c
- file.h
- global.h
- linuxrc.c
- util.c
- util.h
- https://bugzilla.suse.com/show_bug.cgi?id=1199020
When dealing with HiDPI setups it's hard to reproduce issues as you normally don't have exactly the same monitor as the reporter.
This patch adds the `edid` boot option allowing you to define the display size. This works by constructing an EDID firmware record that is subsequently read by the `drm` kernel module.
- https://en.opensuse.org/SDB:Linuxrc#p_edid
```
edid=3840x2160
edid=3840x2160,150
edid=3840x2160,697x392
```
1. This is mainly intended as debug option to be used in virtual environments. Your real monitor may or may not like the EDID data created here.
2. The display width and height **must be below 4096** - so no 8k display specs possible.
3. Obviously, this does not work if you don't use the kernel drm interface to access …
> add EDID boot option to specify arbitrary display sizes (bsc#1199020)

- dialog.c
- dialog.h
- file.c
- file.h
- global.h
- linuxrc.c
- linuxrc.html
- net.c
- https://jira.suse.com/browse/PED-595
ESCON has been deprecated for some time. Remove it from interactive dialogs.
- same for SLE15-SP4: https://github.com/openSUSE/linuxrc/pull/303
- same for SLE15-SP5:
> s390x: remove deprecated ESCON support (jsc#PED-595)

- dialog.c
- net.c
Port https://github.com/openSUSE/linuxrc/pull/295 to SLE15-SP5.
- https://bugzilla.suse.com/show_bug.cgi?id=1198821
Typo: "Hipersocket" should be "HiperSocket".
> fix typo in HiperSocket (bsc#1198821)

- file.c
- file.h
- global.h
- linuxrc.c
- util.c
- util.h
Port https://github.com/openSUSE/linuxrc/pull/310 to Tumbleweed.
- https://jira.suse.com/browse/PED-967
- https://jira.suse.com/browse/PED-3118
wicked now has a more general extension that lists firmware handled network interfaces (not just ibft).
From linuxrc's perspective all these interfaces should just be ignored (not offered for configuration). They are set up by a `wicked ifup all` call.
- https://github.com/openSUSE/installation-images/pull/621
> support more general wicked firmware devices interface (jsc#PED-3118, jsc#PED-967)

- linuxrc.c
- https://bugzilla.suse.com/show_bug.cgi?id=1206460
The `switch_to_fb` option takes care of switching to a graphics console if one becomes available. But linuxrc might have decided earlier to go for text mode because it has seen a serial console.
Revert that decision when switching consoles.
> be careful switch_to_fb option takes care of textmode setting (bsc#1206460)

- file.c
- https://bugzilla.suse.com/show_bug.cgi?id=1208042
NFBT is not detected properly even though `/etc/firmware_types` has an `nbft` entry.
The `fimwaretypes` key was not actually added to the parser.
> really parse 'firmwaretype' key (bsc#1208042)

- checkmedia.c
- global.h
- linuxrc.c
- scsi_rename.c
- url.c
- url.h
- util.c
- https://github.com/openSUSE/hwinfo/pull/134
libhd streamlined its exported symbol list and adjusted its API accordingly.
Adjust to these changes.
> adjust code to updated libhd API

- slp.c
- url.c
Port  https://github.com/openSUSE/linuxrc/pull/324 and  https://github.com/openSUSE/linuxrc/pull/325 to SLE15-SP5.
1.  https://bugzilla.suse.com/show_bug.cgi?id=1213683
When choosing a service type other than the default `install.suse`, linuxrc creates a malformed SLP packet with an incorrect 'Service Type Length' field.
2.  https://bugzilla.suse.com/show_bug.cgi?id=1213531
Add `auto` slp URL parameter to skip interactive dialog presenting a list of matching SLP entries and automatically use the first entry.
> fix length of service type list field in SLP request (bsc#1213683)

- file.c
- global.h
- linuxrc.c
- settings.c
- settings.h
- https://bugzilla.suse.com/show_bug.cgi?id=1218621
`/etc/locale.conf` and `/etc/vconsole.conf` are not created but systemd expects them in the rescue system.
Always create these files (also in the installation system).
As a side effect, the rescue system now also has `/etc/install.inf`.
> write /etc/locale.conf and /etc/vconsole.conf (bsc#1218621)

- dialog.c
- net.c
- https://bugzilla.suse.com/show_bug.cgi?id=1221360
Items in network device list are cut even though there's space available on screen.
Select width of network device list automatically to match item size.
> fix width of network device dialog (bsc#1221360)

- file.c
- global.h
- linuxrc.c
- settings.c
- settings.h
Port https://github.com/openSUSE/linuxrc/pull/329 to SLE15-SP6.
- https://bugzilla.suse.com/show_bug.cgi?id=1218621
`/etc/locale.conf` and `/etc/vconsole.conf` are not created but systemd expects them in the rescue system.
Always create these files (also in the installation system).
As a side effect, the rescue system now also has `/etc/install.inf`.
> write /etc/locale.conf and /etc/vconsole.conf (bsc#1218621, bsc#1222289)

- auto2.c
- global.h
- url.c
- https://bugzilla.suse.com/show_bug.cgi?id=1223326
Port https://github.com/openSUSE/linuxrc/pull/299 to SLE15-SP5.
- https://trello.com/c/CAytlL3W
- https://jira.suse.com/browse/SLE-22578
- https://jira.suse.com/browse/SLE-24584
yast has a `relurl` URL scheme that has different interpretations as to *what* it is relative to depending on the context a URL is used in.
The task is to have something that is always relative to the installation medium (with the repository).
The new `repo` scheme is basically the same as `rel` - that is, relative to the installation repository with the difference that it is never  rewritten to point to the actual location but passed to yast in unmodified form.
There is already a `rel` scheme in linuxrc and a `relurl` scheme in yast. The task is to remove the …
> add 'repo' URL scheme to linuxrc (jsc#SLE-22578, jsc#SLE-24584, bsc#1223326) 

- linuxrc.c
Set the default value of boot option `switch_to_fb` to 1.
This used to be limited to S390X in the SLE15 code stream - mainly to gather some experience in Tumbleweed.
- https://github.com/openSUSE/linuxrc/pull/281
> switch to tty1 if framebuffer device becomes available - now on all architectures (bsc#1225539)

- auto2.c
- https://bugzilla.suse.com/show_bug.cgi?id=1237524
linuxrc can run into a segfault when reading `autoinst.xml` from installer medium.
> fix segfault when reading autoinst.xml from installer medium (bsc#1237524)
