openSUSE/linuxrc

git2log, url.c
That's adjusting to the sle12 workflow.
=> activate network in time on s390x (bnc #915571)

auto2.c, dialog.c, dialog.h, url.c
This improved driver update handling a bit.
=> bnc 901598

net.c, util.c
That's basicalyy the sle12 way, code backported from there.
=> replace internal nfs mount code with call to mount.nfs (bnc #926982)

README.md, auto2.c, checkmedia.c, dialog.c, display.c, file.c, fstype.c, global.h, info.c, install.c, keyboard.c, linuxrc.c, module.c, net.c, scsi_rename.c, settings.c, slp.c, url.c, utf8.c, util.c, util.h
linuxrc now writes a full log to /var/log/linuxrc.log and a shortend
log to /dev/tty3.
=> rewrite linuxrc logging function

file.c, file.h, global.h, linuxrc.c, linuxrc_yast_interface.txt, util.c
* This parameter enables/disables/configures self-update feature.
=> Add SelfUpdate parameter (FATE#319716)

linuxrc.c, util.c
FATE ENTRY: https://fate.suse.com/318971
The script handling is almost completely done in installation-images
=> Implemented Loghost functionality FATE#318971

README.md
Also wrote full working command of makesusecd in the examples.
=> shared libraries corner case mentioned in README

net.c
[bsc#1013605](https://bugzilla.suse.com/show_bug.cgi?id=1013605)
https://trello.com/c/pN6f3kzr
=> Write DHCLIENT_SET_HOSTNAME globally (bsc#1013605)

url.c
It was necessary to adjust the code in a second place.
=> allow reading of config files from instsys location, part 2

linuxrc.c, net.c
Reverts openSUSE/linuxrc#150
Requested by Ihno to get a working build for now.
=> revert latest s390x changes

linuxrc.c, net.c
Added --no-root-update parameter to all the chzdev calls
Tested in actual initrd environment with both Layer2 and Layer3 virtual NICs.
=> Updates for fate#322567

url.c
After checking network cards, go through the remaining network interfaces.
`sort_a_bit()` ensures we try real hardware first and don't try anything twice.
=> try harder to find a suitable network interface (bsc #1068336)

file.c
There was a stray 'else' keyword.
=> fix code flow (bsc #1082468)

keyboard.c
If fd refers to something that another process may be
reading, between select() and read(), something else may consume
the data and result is a stuck read().  Address by making the fd
non blocking and going back to select() when EAGAIN/EWOULDBLOCK
occurs in the read attempt.
=> Eliminate chance of read() hang on size check

auto2.c
The same as https://github.com/openSUSE/linuxrc/pull/179 but for `master` branch.
=> request s390 network device dialog only if really needed (bsc #1106466)

url.c
When searching for the installation repo linuxrc iterates through available local or network devices. As the devices are used in the order they appear in sysfs, it's more or less random.
Sort the device list.
It does not actually solve the issue in [bsc#1058039](https://bugzilla.suse.com/show_bug.cgi?id=1058039) but when you have a lot of devices it becomes a bit annoying that they are used in an apparently random order.
=> iterate through device list in sorted order (bsc#1058039)

Makefile, global.h, linuxrc.c, util.c
Show platform name somewhere, for mainframe systems only.
Replaces https://github.com/openSUSE/linuxrc/pull/203.
=> For jsc#SLE-9474, Added logic to linuxrc.c and util.c to retrieve the

linuxrc.c
- https://bugzilla.suse.com/show_bug.cgi?id=1160378
systemd does not work properly because there's no mountpoint for `/`
linuxrc did a number of things that were needed at some time but no longer are. Fix rescue system setup to ensure it has a mount point for `/`
Related change in installation-images
- https://github.com/openSUSE/installation-images/pull/362
=> fix rescue system setup (bsc#1160378)

file.c
- https://bugzilla.suse.com/show_bug.cgi?id=1179936
- https://trello.com/c/zJMEV1QY
linuxrc doesn't restrict itself to the `<info_file>` section when parsing an AutoYaST file.
Improve the detection of the config file type. Make resaonably sure it sticks to the `<info_file>` section if the file is a human-readable formatted XML.
The next escalation step would be to link against libxml but this seems not yet to be necessary.
This also improves logging - at log level 2 the entire parsed config file is logged.
Recognized valid formattings are
```
<info_file>
foo=10
bar=200
</info_file>
<info_file></info_file>
<info_file/>
```
Do **not** put the element on a single line **if it has content** (it will be ignored):
```
<info_file>foo=10</info_file>
```
=> fix detection of config file type (XML vs. plain text) bsc#1179936

linuxrc.c
- There already have been done lots of changes this year so lets update the copyright date as well
- https://bugzilla.suse.com/show_bug.cgi?id=1184990
=> Set copyright date to "1996-2021" (bsc#1184990)

util.c
- https://bugzilla.suse.com/show_bug.cgi?id=1184550
- https://trello.com/c/J127YQCF
Driver updates may contain a `modules.order` file listing the to-be-loaded modules, one per line, without '.ko' or '.ko.xz' extension.
First, all modules are unloaded in reverse order with `rmmod`, then they are updated, and then re-loaded with `modprobe`.
The modules are not required to be part of the driver update - in this case the entry just triggeres a module load.
The described process was not implemented correctly. In some cases symlinks to non-existing modules were created - which
essentially unloaded and then removed the module from the installation system.
Fix the implementation.
Also, change `modules.order` handling to allow entries in any form (with and without explicit module extension).
=> fix handling of modules.order in driver updates (bsc#1184550)

auto2.c
Port https://github.com/openSUSE/linuxrc/pull/268 to SLE15-SP2.
- https://bugzilla.suse.com/show_bug.cgi?id=1187235
- https://trello.com/c/jRFPOOAW
If linuxrc is passed an `autoyast` option for a rules-based setup, e.g. `autoyast=http://example.com/bar/profiles/` it cannot retrieve that url to test the network connection - because it's a directory.
This leads to the situation that linuxrc may skip the network setup (it doesn't need it in this case).
Assume that a file `rules/rules.xml` exists below the specified directory and try to retrieve that instead. linuxrc does not parse the file, it is only read to ensure the network connection is working.
It is also possible to pass a directory to the `autoyast` option with the intention to select the profile based on the ip or mac address. See …
=> read rules.xml if autoyast option indicates a rules-based setup (bsc#1187235)

file.c
- https://trello.com/c/RfFcN9P7
- https://jira.suse.com/browse/SLE-21308
YaST can be controlled via a number of different environment variables (boot options) during installation. They would show up in the bootloader configuration of the target system - which is usually not wanted.
This can be prevented by making these options 'known' to linuxrc. This has the added benefit that these settings show up in `/etc/install.inf` and they can also be set not only as boot options but also via configuration files (e.g. driver updates, autoyast config).
For this, the [`ptoptions`](https://en.opensuse.org/SDB:Linuxrc#p_ptoptions) config option has been extended to allow pattern matching for environment variable names.
For example `ptoptions=FOO_*` would make linuxrc recognize all options starting …
=> allow option matching based on patterns (jsc#SLE-21308)

linuxrc.c
Port https://github.com/openSUSE/linuxrc/pull/293 to SLE15-SP4.
- https://bugzilla.suse.com/show_bug.cgi?id=1197253
- https://trello.com/c/8u1xvpxB
On machines with large main memory (above roughly 13 TiB), the kernel breaks if zram is used.
Limit zram activation to machines with less than 64 GiB free memory. If really needed it can still be activated using the `zram=1` boot option.
=> do not use zram if there's more than 64 GiB free memory (bsc#1197253)

dialog.c, dialog.h, net.c
- https://jira.suse.com/browse/PED-619
=> s390x: support PCI-attached networking device (jsc#PED-619)

util.c
Port https://github.com/openSUSE/linuxrc/pull/315 to SLE15-SP5.
- https://bugzilla.suse.com/show_bug.cgi?id=1207403
SHA-512 signed repodata lead to very long file names that triggered a buffer overflow.
=> fix buffer overflow in debug log (bsc#1207403)
